# https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md
# https://help.apple.com/xcode/mac/9.0/index.html?localePath=en.lproj#/dev7fe737ce0

# 项目名
name: DoraemonKitDemo
settings:
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: 2J25KWTFJ2
  ENABLE_BITCODE: NO
  GCC_PRECOMPILE_PREFIX_HEADER: YES
  GCC_PREFIX_HEADER: DoraemonKitDemo/DoraemonKitDemo-PrefixHeader.pch
  COMPILER_INDEX_STORE_ENABLE: NO
  IPHONEOS_DEPLOYMENT_TARGET: 12.0
attributes:
  ORGANIZATIONNAME: yixiang

options:
  bundleIdPrefix: com.darkthanblack
  deploymentTarget:
    iOS: 12.0

targets:
  DoraemonKitDemo:
    type: application
    platform: iOS
    platformSuffix: ""
    
    scheme:
      buildImplicitDependencies: true
    
    sources:
      - path: DoraemonKitDemo
        excludes:
          - "**/*.xcodeproj"
          - "**/*.lproj"
          # 额外的资源文件
          - path: DoraemonKitDemo/Base.lproj/LaunchScreen.storyboard
            type: file
            buildPhase: resources
          - path: DoraemonKitDemo/Resource
            type: folder
            buildPhase: resources
    
    resources:
      - path: DoraemonKitDemo/Resource
      - path: DoraemonKitDemo/Assets.xcassets
      - path: DoraemonKitDemo/Base.lproj/LaunchScreen.storyboard
      - path: DoraemonKitDemo/zh-Hans.lproj/LaunchScreen.strings
      - path: DoraemonKitDemo/zh-Hans.lproj/DoraemonKitDemo.strings
      - path: DoraemonKitDemo/en.lproj/DoraemonKitDemo.strings
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.darkthanblack.dokit
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: DoraemonKitDemo/Info.plist
        TARGETED_DEVICE_FAMILY: 1  # iPhone
        IPHONEOS_DEPLOYMENT_TARGET: 12.0
        # LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - "$(PODS_CONFIGURATION_BUILD_DIR)/*"
          - "$(PODS_ROOT)/../../DoraemonKit/Framework"
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
        # 显式写明 COCOAPODS
        OTHER_SWIFT_FLAGS:
          - "$(inherited) -D COCOAPODS"
        # [Fix Xcode 15 Warning: Mixed ObjC ABI](https://stackoverflow.com/questions/77200555)
        OTHER_LDFLAGS:
          - "$(inherited) -ld_classic"
      # 防止 DEBUG 宏莫名丢失
      debug:
        GCC_PREPROCESSOR_DEFINITIONS:
          - $(inherited)
          - DEBUG=1
          - COCOAPODS=1
      release:
        GCC_PREPROCESSOR_DEFINITIONS:
          - $(inherited)
          - COCOAPODS=1
    
    dependencies:
      - framework: Pods_DoraemonKitDemo.framework
        embed: false
      - framework: "$(PODS_ROOT)/../../DoraemonKit/Framework/DoraemonLoadAnalyze.framework"
        embed: false
    
